AtakamaLLC/cloudsync

cloudsync/oauth/oauth_config.py, cloudsync/providers/box.py, cloudsync/tests/test_provider.py, pyproject.toml, requirements.txt
this causes a traceback and failure when requests libs are used without timeouts.   all providers should be brought up to date for this to be merged.
=> assert if requests is used incorrectly

LICENSE, cloudsync/sync/manager.py, cloudsync/sync/state.py, cloudsync/tests/test_sync.py
For oid-as-path providers, we rely on event ordering to determine whether something is a legitimate "trashed" event (actionable) or just a file that's "missing".  This helps resolve event ordering problems when files are removed and created near the same time.
Since we had a situation where an oid_is_path provider caused out-of-order events, this fixes the case where an out-of-order event can cause sync problems.
Notably, however, we are not deferring to "create" in the case where a file is missing.   
While testing this, I found a bug where mkdir on a folder which conflicts a file doesn't properly handle the FileExistsError by marking the sync entry to be "gotten latest" again.
=> Fix out of order events

cloudsync/providers/dropbox.py, cloudsync/runnable.py, cloudsync/tests/test_provider.py
fixes https://vidaid.atlassian.net/browse/BI2-1413
=> Protect file case when globalizing the oid in dropbox

cloudsync/event.py
without an nsid in the label, two namespaces can share state.
=> add namespace id to walk label

.gitignore, cloudsync/sync/state.py, cloudsync/tests/test_sync.py
Main issue: paths in state.py are not normalized, so they must be compared using provider.paths_match()
Secondary issue: though we should not get into the rename codepath when path and sync_path are equivalent (even if the strings don't match) I could not figure out why/how the timestamp of the LOCAL side is updated such that it is newer than the REMOTE timestamp every time through the loop -- this causes an infinite loop. In my contrived test I override the LOCAL provider's hash func to also throw an event, which has the same end result. However, there is no evidence that vfs_provider does this.
Ultimately I think all we need is a simple test that ensures equivalent paths are not treated as renames, instead of this contrived test.
Thoughts?
=> Fix infinite sync loop in rename codepath

cloudsync/sync/manager.py, cloudsync/tests/test_sync.py
@earonesty -- you added the something/nothing checks a couple of months ago, let me know if you see any problems with this change.
on a local delete we set SyncEntry.ignore = discarded, which also sets local and remote .changed=0, which causes us to treat local deletes as "nothing happened"
https://vidaid.atlassian.net/browse/BI2-1531
=> process local delete as "something" to clear backoff

cloudsync/runnable.py, cloudsync/tests/test_cs.py
During shutdown, if a temp file handle is open (download does this), an exception will be raised when the Sync Manager tries to delete the temp directory.  This leaves CryptVFS in a bad state. 
After investigation, the issue looks like that the `runnable.stop()` method calls `done` while the last `do` loop is still occurring. This is what causes the contention. This PR removes the call to `done` and leaves it to the finally block in the `do` loop. `done()` should only be called once the do loop has been stopped.
=> VFM-7427: Fix SyncManager stop()

cloudsync/providers/filesystem.py, cloudsync/tests/test_provider.py
- removed the hack that allowed this test to work for both Namespace objects and strings
- changed it to set namespace by id instead of name (set namespace by name will be deprecated soon)
=> fix namespace test

cloudsync/sync/manager.py, cloudsync/tests/test_sync.py
Another option could be to emit an event and have CryptVFS call walk if we run into this scenario
=> BI2-1245: Sync down file from cloud if parent is deleted on CloudFileExistsError

Makefile, cloudsync/providers/box.py, cloudsync/providers/filesystem.py, cloudsync/sync/manager.py, cloudsync/sync/state.py, cloudsync/tests/test_cs.py, cloudsync/tests/test_sync.py
mark the other side changed if the other side exists and is unchanged, before finalizing syncing a missing file
=> fix handling of missing file during sync

cloudsync/sync/manager.py, cloudsync/tests/test_sync.py
Bump one-off log lines. Don't bump regularly occurring log lines higher than debug.
Three areas that should be logged: 1) Cloudsync errors raised 2) conflict resolution 3) punts
=> VFM-7455 Bump logging levels for sparse events

cloudsync/tests/test_provider.py
Enhance the provider.namespace_id contract to guarantee raising a CloudNamespaceError when the provider is online, and that the namespace property will be None if the provided namespace id is invalid
=> improve the cloud tests for provider namespace id

cloudsync/providers/dropbox.py, cloudsync/tests/test_provider.py
This fixes issues in the dropbox auth and reauth flow where we attempt to open up this url again. For instance, in the cloud service login if we try to authenticate again while the window is open, we will attempt to hit this url. Currently, this will cause an error to be thrown because the `authorization_url` is `None` for Dropbox
=> Populate authorization_url for dropbox

cloudsync/cs.py, cloudsync/long_poll.py, cloudsync/notification.py, cloudsync/runnable.py, cloudsync/tests/test_runnable.py
This will allow us to immediately exit when trying to stop the LongPollManager as opposed to waiting for up to 2 minutes.
=> BI2-1507: Don't wait for long_poll to finish

.travis.yml, Makefile, check-deps.py, pyproject.toml, requirements-dev.txt
It's currently possible for the dependencies of all the individual extras to become out of sync with those of the `all` extra. This leads to unexpected behavior, like pulling in an old version of the Dropbox SDK even after a version constraint has been added to `pyproject.toml`.
* ~Fixes some pylint failures that appear to be new with version 2.5.3.~
* It seems I was mistaken here. The incompatibility was not due to pylint versions, but due to Python versions. The current code passes lint on 3.6, but fails on 3.8. Very strange.
* Adds a script and lint rule that ensure that `all` is in sync with the other extras.
* This grabs them using the [`toml`](https://pypi.org/project/toml/) package, and essentially does a set comparison of the strings. This ensures that version constraints are in …
=> Fix the [all] extra's dependencies

cloudsync/sync/manager.py, cloudsync/tests/fixtures/mock_provider.py, cloudsync/tests/test_cs.py
also set limit on number of punts for the "Attempt dropping dir removal because children appear fully synced" codepath
=> fix for sync loop on non empty folder move

cloudsync/event.py, cloudsync/provider.py, cloudsync/sync/state.py, cloudsync/tests/fixtures/mock_provider.py, cloudsync/tests/test_cs.py, cloudsync/tests/test_events.py
To be used for provider-specific event filtering.
Also considered passing the state interface as a parameter to provider.events() -- a bit cleaner, but this would be a breaking change.
=> Give providers access to sync state interface

cloudsync/sync/state.py
Usually, when a file is renamed from a to b, it is advantageous to move the sync information from the (older) "a" sync entry to the (newer) "b" sync entry. In certain cases, notably office applications, "a" is the new file and "b" is a pre-existing file with sync information that needs to be retained. This change will prevent a prior_ent with less sync information from being used, when the primary ent has more sync information already.
=> Improve prior ent handling when syncing a rename

cloudsync/sync/state.py, cloudsync/tests/test_sync.py, pyproject.toml, requirements.txt
This PR contains the following changes:
1) fixes a bug where the EXISTS enum is used as a bool when exists=None which causes Errors.
2) Bump cloudsync gdrive version
3) Add a test for events with exists=None
=> gdrive-1.0.6 and exists=None fix + test

cloudsync/tests/test_provider.py
This caused 15+ minute teardowns  in test_provider for gdrive and subsequent failure. This seems to fix it
=> Don't flush events on test_provider cleanup

cloudsync/cs.py, cloudsync/event.py, cloudsync/tests/test_cs.py, pyproject.toml, requirements.txt
The problem was related to the walk tag not being removed from the db in the event a bed was forgotten but had not been started which is how we remove beds via econfig. The proposed solution is to use the root_path to construct an unvalidated root to build the walk tag to remove from the db if a validated root is not present.
Misc:
Bump gdrive to 1.0.9
=> BI2-1811: Fix slow activation when re-adding a bed via config

cloudsync/sync/manager.py, cloudsync/sync/state.py, cloudsync/tests/test_sync.py
As before, do not clear backoff on PUNT and REQUEUE, clear backoff on FINISHED.
The change here is to also clear backoff when `sync()` determines that `embrace_change()` need not be called and completes successfully.
=> Clear backoff on successful sync() call

cloudsync/sync/state.py
convert file modification time from a datetime object to the epoch time (either int or float) so that the sync entry can be serialized to the db
=> convert unserializable mtime

cloudsync/event.py, cloudsync/provider.py, cloudsync/tests/test_events.py, cloudsync/tests/test_provider.py
- convert mkdirs errors to CloudRootMissingError in Provider._validate_root()
- don't log repeated CloudTemporaryErrors in EventManager.do()
=> reduce log spam from mkdir errors

cloudsync/sync/state.py, cloudsync/tests/test_sync.py
Fix is_creation to make sure that the existing file is actually changed, meaning that existing files that haven't changed or don't need sync aren't actually creations any more.
Without this fix, a delete on one side and a mirror event on the other side might never sync the delete. This failure to sync is not a busy process, but rather the sync entry (correctly) has Trashed on one side and Exists on the other. Since the changes on both sides were ignored, it will never sync and the condition will persist. With the fix, the deletion takes precedence over the "non-change" on the other side, and the deletion is synced.
This only affects deletions winning out over mirror events. Deletions did (and will continue to) lose out to a create, modify or rename.
=> Fix is_creation to also require a change

cloudsync/smartsync.py, cloudsync/sync/__init__.py, cloudsync/sync/manager.py, cloudsync/sync/state.py, cloudsync/tests/test_sync.py
avoids the overhead of a function call, 
replaces an all-lowercase global function name (which competes in the global namespace with variable names) with an all-uppercase global tuple,
fixes an example of using `other_side` as a variable by mistake, because it LOOKS like a variable, so of course this was bound to happen
=> refactor other_side function to OTHER_SIDE tuple

cloudsync/sync/manager.py, cloudsync/sync/state.py, cloudsync/tests/test_sync.py
Previous iteration blocks synchronization of corrupt files that are detected when downloading the file from the changed side. This enhancement blocks synchronization also when uploading the changed file to the synced side.
=> block corrupt files when uploading or downloading during sync

cloudsync/runnable.py, cloudsync/tests/test_runnable.py, docs/requirements.txt
There were a number of problems that caused the tests in `test_runnable.py` to be flaky.
- When a thread started by a test runs after the test runner has completed running the test, any attempt to log from the thread will result in a `ValueError: I/O operation on closed file`. The runnable tests were starting runnables, but not being careful to stop the runnable thread prior to the end of the test. For whatever reason, suppressing the exception does not prevent the test from failing.
- `Runnable.stop()` had a race condition where it would check if `self.__thread` was not `None` and then use it if so. This variable is changed in other threads, however, so it can be not `None` at the time of the check, but become `None` prior to being dereferenced.
=> Deflake test_runnable tests

cloudsync/sync/manager.py, cloudsync/tests/test_cs.py
Ensure pre-existing conflicted files are not deleted when another sync
takes ownership of them.
When a changed path translates to None, but is still inside the sync
root, just ignore it and do not delete the file/folder (do not assume
that is was moved out of the sync root).
=> Improved nested sync conflict handling
